export enum CategoryType {
    CUSTOMER_CHANNEL = 'CUSTOMER_CHANNEL',
    CUSTOMER_GROUP = 'CUSTOMER_GROUP',
    CUSTOMER_TYPE = 'CUSTOMER_TYPE',
    CUSTOMER_REGION = 'CUSTOMER_REGION',
    PRODUCT_TYPE = 'PRODUCT_TYPE',
    PRODUCT_GROUP = 'PRODUCT_GROUP',
    PRODUCT_SECTOR = 'PRODUCT_SECTOR',
}
